services:
  server:
    build:
      context: .
      target: final
    env_file: .env
    ports:
      - 6000:6000
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5


